pkgname=big-comm-repo
pkgdesc="BIG Community Repository"
depends=('community-keyring')
pkgver=$(date +%y.%m.%d)
pkgrel=$(date +%H%M)
epoch=1
arch=('any')
license=('MIT')
url="https://github.com/big-comm/${pkgname}"
source=("git+${url}.git")
sha256sums=('SKIP')
install="${pkgname}.install"
